name: docker-deploy
on:
  push:
    branches: [ "midocker" ]
jobs:
  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build tag and push 
      uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: mrkaykab/fullstack
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
  Deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-to-dockerhub 
    steps:
    - name: Deploy to Linode instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /root/CICD-react-frontend-class || mkdir -p /root/CICD-react-frontend-class
          cd /root/CICD-react-frontend-class
          if [ ! -d .git ]; then
            git init
            git remote add origin https://github.com/Mrkaykab/CICD-react-frontend-class.git
          fi
          git fetch --all
          git checkout midocker || git checkout -b midocker origin/midocker
          git pull origin midocker
          docker-compose pull
          docker-compose up -d --force-recreate